---
swagger: '2.0'
info:
  description: 'alphabet soup'
  version: 'v1'
  title: 'Challenge cor'
basePath: '/v1'
schemes:
  - 'http'
paths:
  /soup:
    post:
      summary: 'alphabet soup'
      description: 'Search a word in the alphabet soup'
      produces:
        - 'application/json'
      consumes:
       - 'application/json'
      parameters:
      - name: 'soup'
        description: 'alphabet soup'
        in: body
        schema: 
         $ref: '#/definitions/request'
      responses:
        200:
          description: 'Ok'
          schema:
            $ref: '#/definitions/response-ok'
            
definitions:
  request:
    type: 'object'
    properties:
     columns:
      type: 'integer'
      example: 5
     rows:
      type: 'integer'
      example: 5
     search:
      type: 'string'
      example: "OIE"
     soup: 
      type: 'string'
      example: "EAEAEAIIIAEIOIEAIIIAEAEAE"
  response-ok:
    type: 'object'
    properties:
      status_code:
       type: 'number'
      message:
       type: 'object'
       properties:
        horizontal_search:
         type: 'integer'
         example: 2
        vertical_search:
         type: 'integer'
         example: 2
        diagonal_search:
         type: 'integer'
         example: 2
        diagonal_search_reverse:
         type: 'integer'
         example: 2
        total_matches:
         type: 'integer'
         example: 8
        grid:
         type: 'array'
         items: 
          example: ['EAEAE','AIIIA','EIOIE','AIIIA','EAEAE']
       